# Generated by Django 5.1.2 on 2024-11-05 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_barcode_venda_discont_venda_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
