# Generated by Django 5.1.2 on 2024-12-03 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='discont',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='products',
        ),
        migrations.AddField(
            model_name='venda',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='VendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.venda')),
            ],
        ),
    ]
